#SPDX-License-Identifier: MIT-0
---
# tasks file for mariadb2
- name: Instalar {{ software }}
  ansible.builtin.apt: 
    name: "{{ software }}"
    state: present

- name: Arrancar {{ servicio }}
  ansible.builtin.service:
    name: "{{ servicio }}"
    state: restarted
  notify: 
    - copiar_script_sql
    - crear_bd